# Generated by Django 4.2.2 on 2023-06-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('necessary', 'Gastos Necessários'), ('leisure', 'Lazer'), ('savings', 'Economia/Investimentos')], max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
